# Generated by Django 6.0.3 on 2026-04-28 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confluence_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('space_key', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('version_number', models.PositiveIntegerField(default=0)),
                ('parent_confluence_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('body_text', models.TextField(blank=True)),
                ('body_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['space_key', 'title'],
                'indexes': [models.Index(fields=['space_key', 'title'], name='confluence__space_k_b4cf06_idx'), models.Index(fields=['space_key', 'version_number'], name='confluence__space_k_193be9_idx')],
            },
        ),
    ]
