# Generated by Django 6.0.3 on 2026-04-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluencePageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='confluence.confluencepage')),
            ],
            options={
                'ordering': ['page_id', 'position'],
                'indexes': [models.Index(fields=['page', 'position'], name='confluence__page_id_b70fe2_idx'), models.Index(fields=['text_hash'], name='confluence__text_ha_e84972_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'position'), name='unique_confluence_chunk_position')],
            },
        ),
    ]
