# Generated by Django 6.0.3 on 2026-04-28 11:46

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0002_confluencepagechunk'),
        ('shared', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluencepagechunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='confluencepagechunk',
            name='embedded_text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='confluencepagechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='confluencepagechunk',
            name='embedding_model',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
