# Generated by Django 6.0.3 on 2026-04-28 11:50

import django.contrib.postgres.indexes
import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0003_confluencepagechunk_embedded_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='confluencepagechunk',
            index=pgvector.django.indexes.HnswIndex(django.contrib.postgres.indexes.OpClass('embedding', name='vector_cosine_ops'), ef_construction=64, m=16, name='confluence_chunk_embedding_hnsw'),
        ),
    ]
