# Generated by Django 6.0.3 on 2026-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0004_confluencepagechunk_confluence_chunk_embedding_hnsw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfluencePageChunk',
            new_name='Chunk',
        ),
        migrations.AlterModelTable(
            name='chunk',
            table='confluence_confluencepagechunk',
        ),
    ]
