# Generated by Django 6.0.3 on 2026-05-15 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelAskJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('done', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('input_file', models.FileField(upload_to='excel_ask/in/%Y%m%d/')),
                ('result_file', models.FileField(blank=True, max_length=500, upload_to='excel_ask/out/%Y%m%d/')),
                ('sheet', models.CharField(blank=True, max_length=255)),
                ('questions_col', models.CharField(blank=True, max_length=10)),
                ('answers_start_col', models.CharField(blank=True, max_length=10)),
                ('top_k', models.PositiveIntegerField(default=5)),
                ('min_score', models.FloatField()),
                ('save_history', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
