# Generated by Django 6.0.3 on 2026-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('short_answer', models.TextField()),
                ('reasoning_summary', models.TextField(blank=True)),
                ('source_numbers', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('top_k', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='ai_question_created_2e4850_idx'), models.Index(fields=['model_name', 'created_at'], name='ai_question_model_n_3b273a_idx')],
            },
        ),
    ]
