# Generated by Django 6.0.3 on 2026-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerhistory',
            name='min_score',
            field=models.FloatField(default=0.55),
        ),
    ]
